In [2]:
def hdf_to_dataframe(hdf_file_path):
    try:
        import pandas as pd 
        import h5py
        import numpy as np
        import os
        import tables
    except:
        print("Missing Library")
        
    file_n = hdf_file_path.split('.')
    Name = file_n[1]
    A = h5py.File(hdf_file_path, 'r')
    list_1 = list(A.keys())
    list_df = pd.DataFrame()
    list_df2 = pd.DataFrame()
    list_df["keys"] = list_1
    lat = A['lat']   
    lon = A['lon'] 
    data_pd = pd.DataFrame()   
    list_df2["keys"] = list_df["keys"].loc[0:37]
    count = 0
    for keys in list_df2["keys"]:
          if keys == 'ACond_tavg':
              data_arr = A[keys][0,:,:]
              data_pd = pd.DataFrame(data = data_arr)
              data_pd.columns = lon
              data_pd.index = lat
              col_n = Name + keys
              data_pd = pd.melt(data_pd, ignore_index = False, var_name='lon', value_name= col_n)
              print(keys)
          else:
              data_arr = A[keys][0,:,:]
              data = pd.DataFrame(data = data_arr)
              data.index = lat
              col_n = Name + keys
              data = pd.melt(data, ignore_index = False, value_name= col_n)
              data_pd[col_n] = data.loc[:,col_n]
    return data_pd

output = hdf_to_dataframe('GLDAS_CLSM10_M.A200001.021.hdf')

ACond_tavg

In [3]:
output.head()

,lon,A200001ACond_tavg,A200001Albedo_inst,A200001AvgSurfT_inst,A200001CanopInt_inst,A200001ECanop_tavg,A200001ESoil_tavg,A200001Evap_tavg,A200001LWdown_f_tavg,A200001Lwnet_tavg,...,A200001SoilTMP10_29cm_inst,A200001SoilTMP144_295cm_inst,A200001SoilTMP295_1295cm_inst,A200001SoilTMP29_68cm_inst,A200001SoilTMP68_144cm_inst,A200001Swnet_tavg,A200001TVeg_tavg,A200001TWS_inst,A200001Tair_f_inst,A200001Wind_f_inst
/lat,,,,,,,,,,,,,,,,,,,,,
-59.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-58.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-57.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-56.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0
-55.5,-179.5,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0